### ISSUE TITLE
Error message for missing dates (`estimate_static`)

### ISSUE THREAD

**Issue by CarmenTamayo** [epiverse-trace/datadelay#38]
I was getting the following error message when using datadelay's `estimate_static` function:

`Error in data.frame(severity_me = severity_me, severity_lo = severity_lims[[1]], :
arguments imply differing number of rows: 0, 1`

Looking into it, @adamkucharski  helped me figure out that this was because the dataset I was using with cases and deaths was accidentally missing some death dates (as a result of a previous data cleaning step), and the function requires data on each day without skipping any of the dates.

From a user perspective, I believe it would be useful to include this requirement in the documentation more clearly so that users make sure their dataset is in the correct format, and most importantly to include a more informative error message so that users can easily fix the mistake.

**Comment by pratikunterwegs** [comment]
Thanks for flagging this @CarmenTamayo - could you point me to the data that caused this issue? I'm trying to address this issue in #43.

**Comment by CarmenTamayo** [comment]
Thank you for your response @pratikunterwegs, here is an example of some data that results in the above mentioned error due to missing dates:

Creating daily cases/death counts data:
`daily_cases_deaths <- data.frame(case_id = 1:100) %>% 
  mutate(date = sample(seq(as.Date("2023-01-01"), by = "day", length.out = n()))) %>%
  mutate(cases = sample(1:10, replace = T, n())) %>%
  mutate(deaths = sample(0:3, replace = T, n()))`

Introducing missing values:
`daily_cases_deaths <- daily_cases_deaths[-sample(nrow(daily_cases_deaths), 10), ]`

Using `estimate_static` with correct=T, which results in an error:
`onset_to_death_ebola <- epiparameter::epidist_db(
  disease = "Ebola Virus Disease",
  epi_dist = "onset_to_death",
  author = "WHO_Ebola_Response_Team")`

`c_static_cfr <- estimate_static(daily_cases_deaths, epi_dist = onset_to_death_ebola, correct_for_delays = T)`

I hope this is useful, let me know if you need any more information!

**Comment by CarmenTamayo** [comment]
That's great, exactly what I was referring to @pratikunterwegs, I have left a comment on the PR, let me know if this is what you were referring to or if you need anything else
