### ISSUE TITLE
Refactor estimate_severity()

### ISSUE THREAD

**Issue by pratikunterwegs** [epiverse-trace/datadelay#42]
This issue is to report a possible issue with `estimate_severity()`.

Issue: The function description says that the severity is calculated using the cases with known outcomes, which should usually be more than the reported deaths (as some cases will eventually result in deaths). But the function uses total deaths, not total known outcomes, in most cases - am I missing something here?

There are also instances of multiplying `u_t * total_cases`, but `u_t = total_outcomes/total_cases` - does this make sense?

**Comment by adamkucharski** [comment]
The parameterisation follows [Nishiura et al](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0006852), which begins with the 'naive' calculation (`total deaths/total cases`), then calculates an underestimation factor `u_t`, which gives proportion of cases with known outcome. See equations 1-6 in linked paper – the key step is below, with total cases (i.e. sum over `c_i`) appearing in both the expression for `u_t` and the original 'naive' calculation `b_t`. The [likelihood function](https://github.com/epiverse-trace/datadelay/blob/main/R/estimate_severity.R#L30-L44) implemented in `estimate_severity` is equation 9 in that paper.

<img width="576" alt="u_t" src="https://github.com/epiverse-trace/datadelay/assets/8329046/90810b7e-0804-49d3-be03-ba3700a9ca9e">

There are other ways we could parameterise in principle, but think makes sense to keep consistent with the reference we're pointing people to.

**Comment by adamkucharski** [comment]
Following discussion with @CarmenTamayo, I think some of the confusion might come from current description of `known_outcomes()` function – this doesn't require deaths, just case series and delay from onset-to-outcome, so description should be updated to help users: https://github.com/epiverse-trace/datadelay/blob/main/R/known_outcomes.R#L4

Also noticed a potential indexing typo: https://github.com/epiverse-trace/datadelay/blob/main/R/known_outcomes.R#L89

Tagging @thimotei in case he has additional comments.

**Comment by pratikunterwegs** [comment]
Just a follow up to the tests for `known_outcomes()` - I'm editing the test to check that the columns "known_outcomes" and "u_t" are added, but that all existing columns are kept, so that "deaths" is not removed by mistake.

**Comment by CarmenTamayo** [comment]
would it be possible to add an explanation either on the vignettes or documentation of the package of what the values in columns "known_outcomes" and "u_t" represent? it wasn't straight forward for me so I suspect it won't be for external users either
What do you think?

**Comment by pratikunterwegs** [comment]
Yep definitely, can add to the existing PR #44.

**Comment by CarmenTamayo** [comment]
Thank you Pratik!

**Comment by pratikunterwegs** [comment]
Hi @CarmenTamayo - I've added a line on the output of `known_outcomes()` in the vignette which should be added as part of PR # 44, see:

https://github.com/epiverse-trace/datadelay/blob/737f56a82285136199a009dc00fbe7729254cb1c/vignettes/estimate_static_severity.Rmd#L242-L259

**Comment by pratikunterwegs** [comment]
Closing this issue based on explainers above, and secondary issues around `known_outcomes()` have been fixed in #44.
