### ISSUE TITLE
Avoiding use of time varying estimation for small datasets

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/datadelay#45]
For datasets with relatively small number of cases/deaths (like Ebola 1976 example in README), the `estimate_time_varying` function can be unstable, as it's distributing expected timings based on a small number of discrete events, rather than estimating the trend over events occuring daily (like the COVID timeseries).

Therefore, we should limit usage to `estimate_static` for these smaller datasets, e.g. in the README, as the earlier iteration of this package did: https://github.com/adamkucharski/ebola-cfr/blob/main/scripts/main_script.R

If we want to show a figure, we could show how the static CFR calculation changes as more and more data are included. This was in the above script: [CFR_figure.pdf](https://github.com/epiverse-trace/datadelay/files/11678508/CFR_figure.pdf) and in earlier version of this package as a plot, but may have been deprecated to prevent confusion between using an expanding time window of data to fit a static CFR (i.e. this PDF), and fitting a time-varying CFR to a fixed time window of data (i.e. `estimate_time_varying` ). However, given it nicely illustrates the difference between the naive and time-adjusted statitic method, maybe we should include again in the README.

**Comment by pratikunterwegs** [comment]
Thanks - happy to re-add that function as before if the naming could be sorted.

**Comment by pratikunterwegs** [comment]
This issue now potentially tackled in the PR #49, happy to hear feedback!
